"""
Arch-Spatial-Intelligence - Report Generator
==============================================
Generate professional architectural analysis reports in Markdown.
"""

from pathlib import Path
from datetime import datetime


class ReportGenerator:
    """Generate architectural analysis reports."""

    def __init__(self, project_name="Spatial Analysis Report"):
        self.project = project_name
        self.sections = []

    def add_spatial_analysis(self, metrics: dict):
        self.sections.append({"type": "spatial", "title": "Spatial Analysis", "data": metrics})

    def add_facade_analysis(self, data: dict):
        self.sections.append({"type": "facade", "title": "Facade Classification", "data": data})

    def generate_markdown(self) -> str:
        lines = [
            f"# {self.project}",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            "---",
        ]
        for section in self.sections:
            lines.append(f"\\n## {section['title']}\\n")
            data = section["data"]
            if isinstance(data, dict):
                for k, v in data.items():
                    lines.append(f"- **{k}:** {v}")
        lines.append("\\n---\\n_Generated by Arch-Spatial-Intelligence_")
        return "\\n".join(lines)

    def save(self, path="../docs/analysis_report.md"):
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.generate_markdown())
        print(f"Report saved: {path}")
        return path


if __name__ == "__main__":
    r = ReportGenerator("Campus Library Spatial Analysis")
    r.add_spatial_analysis({"Total Area": "850 m^2", "Connectivity": 0.72, "Integration": 0.65})
    r.save()
